// Type declarations for auto-generated cosmos.imports.js
// This file is generated by `cosmos --expose-imports`

import type { RendererConfig, UserModuleWrappers } from 'react-cosmos-core'

declare const cosmosImports: {
  rendererConfig: RendererConfig
  moduleWrappers: UserModuleWrappers
}

export = cosmosImports
