name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint & Format Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run Biome lint
        run: bun run lint

      - name: Run TypeScript type check
        run: bun run typecheck

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB: todoapp_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Run database migrations
        run: bun run db:push
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/todoapp_test
          SKIP_ENV_VALIDATION: true

      - name: Run tests
        run: bun run test
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/todoapp_test
          AUTH_SECRET: test-secret-for-ci
          AUTH_DISCORD_ID: test-id
          AUTH_DISCORD_SECRET: test-secret

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build
        env:
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/todoapp
          AUTH_SECRET: test-secret-for-build
          AUTH_DISCORD_ID: test-id
          AUTH_DISCORD_SECRET: test-secret
